version: 2.1
jobs:
  build:
    parameters:
      node_image:
        type: string

    docker:
    - image: << parameters.node_image >>

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm run build

workflows:
  build:
    jobs:
      - build:
          name: "carbon"
          node_image: "circleci/node:carbon"
      - build:
          name: "dubnium"
          node_image: "circleci/node:dubnium"
      - build:
          name: "erbium"
          node_image: "circleci/node:erbium"