version: 2
jobs:
  build:
    docker:
      - image: node:dubnium-alpine

    working_directory: ~/repo

    steps:
      - run: npm install -g npm
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build
